### PR TITLE
Correct curl command

### PR DESCRIPTION
**Pull request by duganchen**
The command in the README didn't work for me.
```
> curl -o ~/.config/kitty/ https://raw.githubusercontent.com/connorholyday/nord-kitty/master/nord.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0Warning: Failed to create the file /home/dugan/.config/kitty/: Is a directory
100   688  100   688    0     0   1343      0 --:--:-- --:--:-- --:--:--  1341
curl: (23) Failed writing body (0 != 688)
```

### CODE REVIEW

**Comment by connorholyday** [comment]
Does the directory `~/.config/kitty/` exist?

If not then you could either create it yourself or add `--create-dirs` to the end of the curl command like so:
`curl -o ~/.config/kitty/ https://raw.githubusercontent.com/connorholyday/nord-kitty/master/nord.conf --create-dirs`

**Comment by duganchen** [comment]
> Does the directory ~/.config/kitty/ exist?

Yes. That is of course the exact, specific reason why the command in the README failed.

**Comment by connorholyday** [comment]
Great, I think in this instance either the file should be named `nord.conf` rather than `kitty.conf`: or the `--create-dirs` flag should be appended

**Comment by ftassi** [comment]
:+1: for just specifying `~/.config/kitty/nord.conf` for the curl command. Make total sense to me.

**Comment by kovidgoyal** [comment]
Use 
```
kitty +runpy "import os; from kitty.constants import config_dir; from urllib.request import *; urlretrieve('https://raw.githubusercontent.com/connorholyday/nord-kitty/master/nord.conf', os.path.join(config_dir, 'nord.conf'))"
```

No need to hardcode the config dir or depend on curl being availabe.

**Comment by connorholyday** [comment]
I've gone ahead and fixed this up here 071436a by setting it to `~/.config/kitty/nord.conf`. Thanks everyone 👍

**Comment by connorholyday** [comment]
@kovidgoyal I'd rather stick to using curl in the instructions as it's more standard, thank you for your input though I didn't know about that

**Comment by kovidgoyal** [comment]
On Tue, Mar 31, 2020 at 01:49:49PM -0700, Connor Holyday wrote:
> @kovidgoyal I'd rather stick to using curl in the instructions as it's more standard, thank you for your input though I didn't know about that

Up to you, of course, but you can still have kitty print out its config
dir to use with curl, so you dont have to hard code it.


kitty +runpy "from kitty.constants import config_dir; print(config_dir, end='')"

**Pull request closed without merging**
